// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package evm

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_Params                                          protoreflect.MessageDescriptor
	fd_Params_priority_normalizer                      protoreflect.FieldDescriptor
	fd_Params_base_fee_per_gas                         protoreflect.FieldDescriptor
	fd_Params_minimum_fee_per_gas                      protoreflect.FieldDescriptor
	fd_Params_max_dynamic_base_fee_upward_adjustment   protoreflect.FieldDescriptor
	fd_Params_max_dynamic_base_fee_downward_adjustment protoreflect.FieldDescriptor
	fd_Params_target_gas_used_per_block                protoreflect.FieldDescriptor
	fd_Params_maximum_fee_per_gas                      protoreflect.FieldDescriptor
	fd_Params_init_eni_amount                          protoreflect.FieldDescriptor
	fd_Params_init_eni_address                         protoreflect.FieldDescriptor
)

func init() {
	file_goeni_evm_params_proto_init()
	md_Params = File_goeni_evm_params_proto.Messages().ByName("Params")
	fd_Params_priority_normalizer = md_Params.Fields().ByName("priority_normalizer")
	fd_Params_base_fee_per_gas = md_Params.Fields().ByName("base_fee_per_gas")
	fd_Params_minimum_fee_per_gas = md_Params.Fields().ByName("minimum_fee_per_gas")
	fd_Params_max_dynamic_base_fee_upward_adjustment = md_Params.Fields().ByName("max_dynamic_base_fee_upward_adjustment")
	fd_Params_max_dynamic_base_fee_downward_adjustment = md_Params.Fields().ByName("max_dynamic_base_fee_downward_adjustment")
	fd_Params_target_gas_used_per_block = md_Params.Fields().ByName("target_gas_used_per_block")
	fd_Params_maximum_fee_per_gas = md_Params.Fields().ByName("maximum_fee_per_gas")
	fd_Params_init_eni_amount = md_Params.Fields().ByName("init_eni_amount")
	fd_Params_init_eni_address = md_Params.Fields().ByName("init_eni_address")
}

var _ protoreflect.Message = (*fastReflection_Params)(nil)

type fastReflection_Params Params

func (x *Params) ProtoReflect() protoreflect.Message {
	return (*fastReflection_Params)(x)
}

func (x *Params) slowProtoReflect() protoreflect.Message {
	mi := &file_goeni_evm_params_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_Params_messageType fastReflection_Params_messageType
var _ protoreflect.MessageType = fastReflection_Params_messageType{}

type fastReflection_Params_messageType struct{}

func (x fastReflection_Params_messageType) Zero() protoreflect.Message {
	return (*fastReflection_Params)(nil)
}
func (x fastReflection_Params_messageType) New() protoreflect.Message {
	return new(fastReflection_Params)
}
func (x fastReflection_Params_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_Params
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_Params) Descriptor() protoreflect.MessageDescriptor {
	return md_Params
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_Params) Type() protoreflect.MessageType {
	return _fastReflection_Params_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_Params) New() protoreflect.Message {
	return new(fastReflection_Params)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_Params) Interface() protoreflect.ProtoMessage {
	return (*Params)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_Params) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.PriorityNormalizer != "" {
		value := protoreflect.ValueOfString(x.PriorityNormalizer)
		if !f(fd_Params_priority_normalizer, value) {
			return
		}
	}
	if x.BaseFeePerGas != "" {
		value := protoreflect.ValueOfString(x.BaseFeePerGas)
		if !f(fd_Params_base_fee_per_gas, value) {
			return
		}
	}
	if x.MinimumFeePerGas != "" {
		value := protoreflect.ValueOfString(x.MinimumFeePerGas)
		if !f(fd_Params_minimum_fee_per_gas, value) {
			return
		}
	}
	if x.MaxDynamicBaseFeeUpwardAdjustment != "" {
		value := protoreflect.ValueOfString(x.MaxDynamicBaseFeeUpwardAdjustment)
		if !f(fd_Params_max_dynamic_base_fee_upward_adjustment, value) {
			return
		}
	}
	if x.MaxDynamicBaseFeeDownwardAdjustment != "" {
		value := protoreflect.ValueOfString(x.MaxDynamicBaseFeeDownwardAdjustment)
		if !f(fd_Params_max_dynamic_base_fee_downward_adjustment, value) {
			return
		}
	}
	if x.TargetGasUsedPerBlock != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TargetGasUsedPerBlock)
		if !f(fd_Params_target_gas_used_per_block, value) {
			return
		}
	}
	if x.MaximumFeePerGas != "" {
		value := protoreflect.ValueOfString(x.MaximumFeePerGas)
		if !f(fd_Params_maximum_fee_per_gas, value) {
			return
		}
	}
	if x.InitEniAmount != "" {
		value := protoreflect.ValueOfString(x.InitEniAmount)
		if !f(fd_Params_init_eni_amount, value) {
			return
		}
	}
	if x.InitEniAddress != "" {
		value := protoreflect.ValueOfString(x.InitEniAddress)
		if !f(fd_Params_init_eni_address, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_Params) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "goeni.evm.Params.priority_normalizer":
		return x.PriorityNormalizer != ""
	case "goeni.evm.Params.base_fee_per_gas":
		return x.BaseFeePerGas != ""
	case "goeni.evm.Params.minimum_fee_per_gas":
		return x.MinimumFeePerGas != ""
	case "goeni.evm.Params.max_dynamic_base_fee_upward_adjustment":
		return x.MaxDynamicBaseFeeUpwardAdjustment != ""
	case "goeni.evm.Params.max_dynamic_base_fee_downward_adjustment":
		return x.MaxDynamicBaseFeeDownwardAdjustment != ""
	case "goeni.evm.Params.target_gas_used_per_block":
		return x.TargetGasUsedPerBlock != uint64(0)
	case "goeni.evm.Params.maximum_fee_per_gas":
		return x.MaximumFeePerGas != ""
	case "goeni.evm.Params.init_eni_amount":
		return x.InitEniAmount != ""
	case "goeni.evm.Params.init_eni_address":
		return x.InitEniAddress != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: goeni.evm.Params"))
		}
		panic(fmt.Errorf("message goeni.evm.Params does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "goeni.evm.Params.priority_normalizer":
		x.PriorityNormalizer = ""
	case "goeni.evm.Params.base_fee_per_gas":
		x.BaseFeePerGas = ""
	case "goeni.evm.Params.minimum_fee_per_gas":
		x.MinimumFeePerGas = ""
	case "goeni.evm.Params.max_dynamic_base_fee_upward_adjustment":
		x.MaxDynamicBaseFeeUpwardAdjustment = ""
	case "goeni.evm.Params.max_dynamic_base_fee_downward_adjustment":
		x.MaxDynamicBaseFeeDownwardAdjustment = ""
	case "goeni.evm.Params.target_gas_used_per_block":
		x.TargetGasUsedPerBlock = uint64(0)
	case "goeni.evm.Params.maximum_fee_per_gas":
		x.MaximumFeePerGas = ""
	case "goeni.evm.Params.init_eni_amount":
		x.InitEniAmount = ""
	case "goeni.evm.Params.init_eni_address":
		x.InitEniAddress = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: goeni.evm.Params"))
		}
		panic(fmt.Errorf("message goeni.evm.Params does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_Params) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "goeni.evm.Params.priority_normalizer":
		value := x.PriorityNormalizer
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.base_fee_per_gas":
		value := x.BaseFeePerGas
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.minimum_fee_per_gas":
		value := x.MinimumFeePerGas
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.max_dynamic_base_fee_upward_adjustment":
		value := x.MaxDynamicBaseFeeUpwardAdjustment
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.max_dynamic_base_fee_downward_adjustment":
		value := x.MaxDynamicBaseFeeDownwardAdjustment
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.target_gas_used_per_block":
		value := x.TargetGasUsedPerBlock
		return protoreflect.ValueOfUint64(value)
	case "goeni.evm.Params.maximum_fee_per_gas":
		value := x.MaximumFeePerGas
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.init_eni_amount":
		value := x.InitEniAmount
		return protoreflect.ValueOfString(value)
	case "goeni.evm.Params.init_eni_address":
		value := x.InitEniAddress
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: goeni.evm.Params"))
		}
		panic(fmt.Errorf("message goeni.evm.Params does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "goeni.evm.Params.priority_normalizer":
		x.PriorityNormalizer = value.Interface().(string)
	case "goeni.evm.Params.base_fee_per_gas":
		x.BaseFeePerGas = value.Interface().(string)
	case "goeni.evm.Params.minimum_fee_per_gas":
		x.MinimumFeePerGas = value.Interface().(string)
	case "goeni.evm.Params.max_dynamic_base_fee_upward_adjustment":
		x.MaxDynamicBaseFeeUpwardAdjustment = value.Interface().(string)
	case "goeni.evm.Params.max_dynamic_base_fee_downward_adjustment":
		x.MaxDynamicBaseFeeDownwardAdjustment = value.Interface().(string)
	case "goeni.evm.Params.target_gas_used_per_block":
		x.TargetGasUsedPerBlock = value.Uint()
	case "goeni.evm.Params.maximum_fee_per_gas":
		x.MaximumFeePerGas = value.Interface().(string)
	case "goeni.evm.Params.init_eni_amount":
		x.InitEniAmount = value.Interface().(string)
	case "goeni.evm.Params.init_eni_address":
		x.InitEniAddress = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: goeni.evm.Params"))
		}
		panic(fmt.Errorf("message goeni.evm.Params does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "goeni.evm.Params.priority_normalizer":
		panic(fmt.Errorf("field priority_normalizer of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.base_fee_per_gas":
		panic(fmt.Errorf("field base_fee_per_gas of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.minimum_fee_per_gas":
		panic(fmt.Errorf("field minimum_fee_per_gas of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.max_dynamic_base_fee_upward_adjustment":
		panic(fmt.Errorf("field max_dynamic_base_fee_upward_adjustment of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.max_dynamic_base_fee_downward_adjustment":
		panic(fmt.Errorf("field max_dynamic_base_fee_downward_adjustment of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.target_gas_used_per_block":
		panic(fmt.Errorf("field target_gas_used_per_block of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.maximum_fee_per_gas":
		panic(fmt.Errorf("field maximum_fee_per_gas of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.init_eni_amount":
		panic(fmt.Errorf("field init_eni_amount of message goeni.evm.Params is not mutable"))
	case "goeni.evm.Params.init_eni_address":
		panic(fmt.Errorf("field init_eni_address of message goeni.evm.Params is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: goeni.evm.Params"))
		}
		panic(fmt.Errorf("message goeni.evm.Params does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_Params) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "goeni.evm.Params.priority_normalizer":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.base_fee_per_gas":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.minimum_fee_per_gas":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.max_dynamic_base_fee_upward_adjustment":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.max_dynamic_base_fee_downward_adjustment":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.target_gas_used_per_block":
		return protoreflect.ValueOfUint64(uint64(0))
	case "goeni.evm.Params.maximum_fee_per_gas":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.init_eni_amount":
		return protoreflect.ValueOfString("")
	case "goeni.evm.Params.init_eni_address":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: goeni.evm.Params"))
		}
		panic(fmt.Errorf("message goeni.evm.Params does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_Params) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in goeni.evm.Params", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_Params) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_Params) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_Params) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_Params) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.PriorityNormalizer)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.BaseFeePerGas)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MinimumFeePerGas)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MaxDynamicBaseFeeUpwardAdjustment)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.MaxDynamicBaseFeeDownwardAdjustment)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.TargetGasUsedPerBlock != 0 {
			n += 1 + runtime.Sov(uint64(x.TargetGasUsedPerBlock))
		}
		l = len(x.MaximumFeePerGas)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.InitEniAmount)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.InitEniAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.InitEniAddress) > 0 {
			i -= len(x.InitEniAddress)
			copy(dAtA[i:], x.InitEniAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.InitEniAddress)))
			i--
			dAtA[i] = 0x7a
		}
		if len(x.InitEniAmount) > 0 {
			i -= len(x.InitEniAmount)
			copy(dAtA[i:], x.InitEniAmount)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.InitEniAmount)))
			i--
			dAtA[i] = 0x72
		}
		if len(x.MaximumFeePerGas) > 0 {
			i -= len(x.MaximumFeePerGas)
			copy(dAtA[i:], x.MaximumFeePerGas)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaximumFeePerGas)))
			i--
			dAtA[i] = 0x6a
		}
		if x.TargetGasUsedPerBlock != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TargetGasUsedPerBlock))
			i--
			dAtA[i] = 0x60
		}
		if len(x.MaxDynamicBaseFeeDownwardAdjustment) > 0 {
			i -= len(x.MaxDynamicBaseFeeDownwardAdjustment)
			copy(dAtA[i:], x.MaxDynamicBaseFeeDownwardAdjustment)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaxDynamicBaseFeeDownwardAdjustment)))
			i--
			dAtA[i] = 0x5a
		}
		if len(x.MaxDynamicBaseFeeUpwardAdjustment) > 0 {
			i -= len(x.MaxDynamicBaseFeeUpwardAdjustment)
			copy(dAtA[i:], x.MaxDynamicBaseFeeUpwardAdjustment)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MaxDynamicBaseFeeUpwardAdjustment)))
			i--
			dAtA[i] = 0x52
		}
		if len(x.MinimumFeePerGas) > 0 {
			i -= len(x.MinimumFeePerGas)
			copy(dAtA[i:], x.MinimumFeePerGas)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.MinimumFeePerGas)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.BaseFeePerGas) > 0 {
			i -= len(x.BaseFeePerGas)
			copy(dAtA[i:], x.BaseFeePerGas)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.BaseFeePerGas)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.PriorityNormalizer) > 0 {
			i -= len(x.PriorityNormalizer)
			copy(dAtA[i:], x.PriorityNormalizer)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PriorityNormalizer)))
			i--
			dAtA[i] = 0x12
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*Params)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Params: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PriorityNormalizer = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.BaseFeePerGas = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MinimumFeePerGas = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 10:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeUpwardAdjustment", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaxDynamicBaseFeeUpwardAdjustment = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 11:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeDownwardAdjustment", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaxDynamicBaseFeeDownwardAdjustment = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 12:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TargetGasUsedPerBlock", wireType)
				}
				x.TargetGasUsedPerBlock = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TargetGasUsedPerBlock |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 13:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field MaximumFeePerGas", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.MaximumFeePerGas = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 14:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InitEniAmount", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.InitEniAmount = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 15:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field InitEniAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.InitEniAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: goeni/evm/params.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the parameters for the module
type Params struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// string base_denom = 1 [
	//
	//	(gogoproto.moretags)   = "yaml:\"base_denom\"",
	//	(gogoproto.jsontag) = "base_denom"
	//
	// ];
	PriorityNormalizer                  string `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3" json:"priority_normalizer,omitempty"`
	BaseFeePerGas                       string `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3" json:"base_fee_per_gas,omitempty"`
	MinimumFeePerGas                    string `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3" json:"minimum_fee_per_gas,omitempty"`
	MaxDynamicBaseFeeUpwardAdjustment   string `protobuf:"bytes,10,opt,name=max_dynamic_base_fee_upward_adjustment,json=maxDynamicBaseFeeUpwardAdjustment,proto3" json:"max_dynamic_base_fee_upward_adjustment,omitempty"`
	MaxDynamicBaseFeeDownwardAdjustment string `protobuf:"bytes,11,opt,name=max_dynamic_base_fee_downward_adjustment,json=maxDynamicBaseFeeDownwardAdjustment,proto3" json:"max_dynamic_base_fee_downward_adjustment,omitempty"`
	TargetGasUsedPerBlock               uint64 `protobuf:"varint,12,opt,name=target_gas_used_per_block,json=targetGasUsedPerBlock,proto3" json:"target_gas_used_per_block,omitempty"`
	MaximumFeePerGas                    string `protobuf:"bytes,13,opt,name=maximum_fee_per_gas,json=maximumFeePerGas,proto3" json:"maximum_fee_per_gas,omitempty"`
	InitEniAmount                       string `protobuf:"bytes,14,opt,name=init_eni_amount,json=initEniAmount,proto3" json:"init_eni_amount,omitempty"`
	InitEniAddress                      string `protobuf:"bytes,15,opt,name=init_eni_address,json=initEniAddress,proto3" json:"init_eni_address,omitempty"`
}

func (x *Params) Reset() {
	*x = Params{}
	if protoimpl.UnsafeEnabled {
		mi := &file_goeni_evm_params_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_goeni_evm_params_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetPriorityNormalizer() string {
	if x != nil {
		return x.PriorityNormalizer
	}
	return ""
}

func (x *Params) GetBaseFeePerGas() string {
	if x != nil {
		return x.BaseFeePerGas
	}
	return ""
}

func (x *Params) GetMinimumFeePerGas() string {
	if x != nil {
		return x.MinimumFeePerGas
	}
	return ""
}

func (x *Params) GetMaxDynamicBaseFeeUpwardAdjustment() string {
	if x != nil {
		return x.MaxDynamicBaseFeeUpwardAdjustment
	}
	return ""
}

func (x *Params) GetMaxDynamicBaseFeeDownwardAdjustment() string {
	if x != nil {
		return x.MaxDynamicBaseFeeDownwardAdjustment
	}
	return ""
}

func (x *Params) GetTargetGasUsedPerBlock() uint64 {
	if x != nil {
		return x.TargetGasUsedPerBlock
	}
	return 0
}

func (x *Params) GetMaximumFeePerGas() string {
	if x != nil {
		return x.MaximumFeePerGas
	}
	return ""
}

func (x *Params) GetInitEniAmount() string {
	if x != nil {
		return x.InitEniAmount
	}
	return ""
}

func (x *Params) GetInitEniAddress() string {
	if x != nil {
		return x.InitEniAddress
	}
	return ""
}

var File_goeni_evm_params_proto protoreflect.FileDescriptor

var file_goeni_evm_params_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x6f, 0x65, 0x6e, 0x69, 0x2f, 0x65, 0x76, 0x6d, 0x2f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x6f, 0x65, 0x6e, 0x69, 0x2e,
	0x65, 0x76, 0x6d, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc2, 0x09, 0x0a, 0x06, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x89, 0x01, 0x0a, 0x13, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74,
	0x79, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x58, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65,
	0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xea, 0xde, 0x1f, 0x13, 0x70, 0x72, 0x69, 0x6f, 0x72,
	0x69, 0x74, 0x79, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0xf2, 0xde,
	0x1f, 0x1a, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79,
	0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72, 0x22, 0x52, 0x12, 0x70, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x72,
	0x12, 0x7b, 0x0a, 0x10, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72,
	0x5f, 0x67, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x42, 0x52, 0xc8, 0xde, 0x1f, 0x00,
	0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f,
	0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xea,
	0xde, 0x1f, 0x10, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x67, 0x61, 0x73, 0xf2, 0xde, 0x1f, 0x17, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x73, 0x22, 0x52, 0x0d,
	0x62, 0x61, 0x73, 0x65, 0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x47, 0x61, 0x73, 0x12, 0x87, 0x01,
	0x0a, 0x13, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65,
	0x72, 0x5f, 0x67, 0x61, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x42, 0x58, 0xc8, 0xde, 0x1f,
	0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69,
	0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63,
	0xea, 0xde, 0x1f, 0x13, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x66, 0x65, 0x65, 0x5f,
	0x70, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x73, 0xf2, 0xde, 0x1f, 0x1a, 0x79, 0x61, 0x6d, 0x6c, 0x3a,
	0x22, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72,
	0x5f, 0x67, 0x61, 0x73, 0x22, 0x52, 0x10, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x46, 0x65,
	0x65, 0x50, 0x65, 0x72, 0x47, 0x61, 0x73, 0x12, 0xd1, 0x01, 0x0a, 0x26, 0x6d, 0x61, 0x78, 0x5f,
	0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x65, 0x65,
	0x5f, 0x75, 0x70, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x42, 0x7e, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde,
	0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d,
	0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65, 0x63, 0xea, 0xde, 0x1f,
	0x26, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x75, 0x70, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x64, 0x6a,
	0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0xf2, 0xde, 0x1f, 0x2d, 0x79, 0x61, 0x6d, 0x6c, 0x3a,
	0x22, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x75, 0x70, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x64, 0x6a,
	0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x52, 0x21, 0x6d, 0x61, 0x78, 0x44, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x42, 0x61, 0x73, 0x65, 0x46, 0x65, 0x65, 0x55, 0x70, 0x77, 0x61, 0x72,
	0x64, 0x41, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0xda, 0x01, 0x0a, 0x28,
	0x6d, 0x61, 0x78, 0x5f, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65,
	0x5f, 0x66, 0x65, 0x65, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x64,
	0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x42, 0x82,
	0x01, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73,
	0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63,
	0x79, 0x44, 0x65, 0x63, 0xea, 0xde, 0x1f, 0x28, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x64, 0x6f, 0x77,
	0x6e, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74,
	0xf2, 0xde, 0x1f, 0x2f, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x6d, 0x61, 0x78, 0x5f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x66, 0x65, 0x65, 0x5f, 0x64,
	0x6f, 0x77, 0x6e, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0x52, 0x23, 0x6d, 0x61, 0x78, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x42,
	0x61, 0x73, 0x65, 0x46, 0x65, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x77, 0x61, 0x72, 0x64, 0x41, 0x64,
	0x6a, 0x75, 0x73, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x19, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x67, 0x61, 0x73, 0x5f, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x70, 0x65, 0x72, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x15, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x47, 0x61, 0x73, 0x55, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x12, 0x87, 0x01, 0x0a, 0x13, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x66,
	0x65, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x58, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61,
	0x63, 0x79, 0x44, 0x65, 0x63, 0xea, 0xde, 0x1f, 0x13, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d,
	0x5f, 0x66, 0x65, 0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x73, 0xf2, 0xde, 0x1f, 0x1a,
	0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x66, 0x65,
	0x65, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x67, 0x61, 0x73, 0x22, 0x52, 0x10, 0x6d, 0x61, 0x78, 0x69,
	0x6d, 0x75, 0x6d, 0x46, 0x65, 0x65, 0x50, 0x65, 0x72, 0x47, 0x61, 0x73, 0x12, 0x55, 0x0a, 0x0f,
	0x69, 0x6e, 0x69, 0x74, 0x5f, 0x65, 0x6e, 0x69, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2d, 0xea, 0xde, 0x1f, 0x0f, 0x69, 0x6e, 0x69, 0x74, 0x5f,
	0x65, 0x6e, 0x69, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0xf2, 0xde, 0x1f, 0x16, 0x79, 0x61,
	0x6d, 0x6c, 0x3a, 0x22, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x65, 0x6e, 0x69, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x52, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x69, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x59, 0x0a, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x65, 0x6e, 0x69, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x42, 0x2f, 0xea,
	0xde, 0x1f, 0x10, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x65, 0x6e, 0x69, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0xf2, 0xde, 0x1f, 0x17, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x69, 0x6e, 0x69,
	0x74, 0x5f, 0x65, 0x6e, 0x69, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x52, 0x0e,
	0x69, 0x6e, 0x69, 0x74, 0x45, 0x6e, 0x69, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x8c,
	0x01, 0x0a, 0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x65, 0x6e, 0x69, 0x2e, 0x65, 0x76, 0x6d,
	0x42, 0x0b, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x69, 0x2d,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x67, 0x6f, 0x2d, 0x65, 0x6e, 0x69, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x67, 0x6f, 0x65, 0x6e, 0x69, 0x2f, 0x65, 0x76, 0x6d, 0xa2, 0x02, 0x03, 0x47, 0x45, 0x58,
	0xaa, 0x02, 0x09, 0x47, 0x6f, 0x65, 0x6e, 0x69, 0x2e, 0x45, 0x76, 0x6d, 0xca, 0x02, 0x09, 0x47,
	0x6f, 0x65, 0x6e, 0x69, 0x5c, 0x45, 0x76, 0x6d, 0xe2, 0x02, 0x15, 0x47, 0x6f, 0x65, 0x6e, 0x69,
	0x5c, 0x45, 0x76, 0x6d, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0xea, 0x02, 0x0a, 0x47, 0x6f, 0x65, 0x6e, 0x69, 0x3a, 0x3a, 0x45, 0x76, 0x6d, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_goeni_evm_params_proto_rawDescOnce sync.Once
	file_goeni_evm_params_proto_rawDescData = file_goeni_evm_params_proto_rawDesc
)

func file_goeni_evm_params_proto_rawDescGZIP() []byte {
	file_goeni_evm_params_proto_rawDescOnce.Do(func() {
		file_goeni_evm_params_proto_rawDescData = protoimpl.X.CompressGZIP(file_goeni_evm_params_proto_rawDescData)
	})
	return file_goeni_evm_params_proto_rawDescData
}

var file_goeni_evm_params_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_goeni_evm_params_proto_goTypes = []interface{}{
	(*Params)(nil), // 0: goeni.evm.Params
}
var file_goeni_evm_params_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_goeni_evm_params_proto_init() }
func file_goeni_evm_params_proto_init() {
	if File_goeni_evm_params_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_goeni_evm_params_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Params); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_goeni_evm_params_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goeni_evm_params_proto_goTypes,
		DependencyIndexes: file_goeni_evm_params_proto_depIdxs,
		MessageInfos:      file_goeni_evm_params_proto_msgTypes,
	}.Build()
	File_goeni_evm_params_proto = out.File
	file_goeni_evm_params_proto_rawDesc = nil
	file_goeni_evm_params_proto_goTypes = nil
	file_goeni_evm_params_proto_depIdxs = nil
}
