// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: goeni/evm/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module
type Params struct {
	// string base_denom = 1 [
	//   (gogoproto.moretags)   = "yaml:\"base_denom\"",
	//   (gogoproto.jsontag) = "base_denom"
	// ];
	PriorityNormalizer                  cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=priority_normalizer,json=priorityNormalizer,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"priority_normalizer" yaml:"priority_normalizer"`
	BaseFeePerGas                       cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=base_fee_per_gas,json=baseFeePerGas,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"base_fee_per_gas" yaml:"base_fee_per_gas"`
	MinimumFeePerGas                    cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=minimum_fee_per_gas,json=minimumFeePerGas,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"minimum_fee_per_gas" yaml:"minimum_fee_per_gas"`
	MaxDynamicBaseFeeUpwardAdjustment   cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=max_dynamic_base_fee_upward_adjustment,json=maxDynamicBaseFeeUpwardAdjustment,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_dynamic_base_fee_upward_adjustment" yaml:"max_dynamic_base_fee_upward_adjustment"`
	MaxDynamicBaseFeeDownwardAdjustment cosmossdk_io_math.LegacyDec `protobuf:"bytes,11,opt,name=max_dynamic_base_fee_downward_adjustment,json=maxDynamicBaseFeeDownwardAdjustment,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"max_dynamic_base_fee_downward_adjustment" yaml:"max_dynamic_base_fee_downward_adjustment"`
	TargetGasUsedPerBlock               uint64                      `protobuf:"varint,12,opt,name=target_gas_used_per_block,json=targetGasUsedPerBlock,proto3" json:"target_gas_used_per_block,omitempty"`
	MaximumFeePerGas                    cosmossdk_io_math.LegacyDec `protobuf:"bytes,13,opt,name=maximum_fee_per_gas,json=maximumFeePerGas,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"maximum_fee_per_gas" yaml:"maximum_fee_per_gas"`
	InitEniAmount                       string                      `protobuf:"bytes,14,opt,name=init_eni_amount,json=initEniAmount,proto3" json:"init_eni_amount" yaml:"init_eni_amount"`
	InitEniAddress                      string                      `protobuf:"bytes,15,opt,name=init_eni_address,json=initEniAddress,proto3" json:"init_eni_address" yaml:"init_eni_address"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6eb2f0ab511e6217, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTargetGasUsedPerBlock() uint64 {
	if m != nil {
		return m.TargetGasUsedPerBlock
	}
	return 0
}

func (m *Params) GetInitEniAmount() string {
	if m != nil {
		return m.InitEniAmount
	}
	return ""
}

func (m *Params) GetInitEniAddress() string {
	if m != nil {
		return m.InitEniAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*Params)(nil), "goeni.evm.Params")
}

func init() { proto.RegisterFile("goeni/evm/params.proto", fileDescriptor_6eb2f0ab511e6217) }

var fileDescriptor_6eb2f0ab511e6217 = []byte{
	// 562 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x31, 0x6f, 0xd3, 0x4e,
	0x1c, 0x8d, 0xff, 0xff, 0xaa, 0x52, 0x0d, 0x6d, 0x23, 0x17, 0x8a, 0x29, 0x92, 0x5d, 0x8c, 0x04,
	0x59, 0x12, 0x0f, 0x2c, 0x88, 0x2d, 0x51, 0xa0, 0x0b, 0x42, 0x91, 0xa5, 0x48, 0xc0, 0x62, 0x5d,
	0xec, 0x1f, 0xce, 0xd1, 0xdc, 0x9d, 0x75, 0x77, 0x6e, 0x13, 0x90, 0x18, 0x58, 0x10, 0x1b, 0x9f,
	0x89, 0xa9, 0x63, 0xd9, 0x50, 0x07, 0x0b, 0x25, 0x5b, 0xc7, 0x7c, 0x02, 0xe4, 0x73, 0x9a, 0x14,
	0xc7, 0x42, 0xee, 0x66, 0xbf, 0xf7, 0xee, 0xe9, 0xfd, 0xee, 0xde, 0x9d, 0xbe, 0x1f, 0x31, 0xa0,
	0xd8, 0x85, 0x13, 0xe2, 0xc6, 0x88, 0x23, 0x22, 0x5a, 0x31, 0x67, 0x92, 0x19, 0x5b, 0x0a, 0x6f,
	0xc1, 0x09, 0x39, 0xb8, 0x13, 0xb1, 0x88, 0x29, 0xd4, 0xcd, 0xbe, 0x72, 0x81, 0xf3, 0x63, 0x4b,
	0xdf, 0xec, 0xa9, 0x15, 0xc6, 0x37, 0x4d, 0xdf, 0x8b, 0x39, 0x66, 0x1c, 0xcb, 0x89, 0x4f, 0x19,
	0x27, 0x68, 0x84, 0x3f, 0x02, 0x37, 0xff, 0x3b, 0xd4, 0x1a, 0x5b, 0x9d, 0x37, 0x67, 0xa9, 0x5d,
	0xbb, 0x48, 0xed, 0x07, 0x01, 0x13, 0x84, 0x09, 0x11, 0x1e, 0xb7, 0x30, 0x73, 0x09, 0x92, 0xc3,
	0xd6, 0x2b, 0x88, 0x50, 0x30, 0xe9, 0x42, 0x70, 0x99, 0xda, 0x65, 0x0e, 0xf3, 0xd4, 0x3e, 0x98,
	0x20, 0x32, 0x7a, 0xee, 0x94, 0x90, 0x8e, 0x67, 0x5c, 0xa1, 0xaf, 0x97, 0xa0, 0xf1, 0x49, 0xaf,
	0x0f, 0x90, 0x00, 0xff, 0x3d, 0x80, 0x1f, 0x03, 0xf7, 0x23, 0x24, 0xcc, 0xff, 0x55, 0x0e, 0xaf,
	0x5a, 0x8e, 0xb5, 0xe5, 0xf3, 0xd4, 0xbe, 0x97, 0x87, 0x28, 0x32, 0x8e, 0xb7, 0x9d, 0x41, 0x2f,
	0x01, 0x7a, 0xc0, 0x8f, 0x90, 0x30, 0xbe, 0x6a, 0xfa, 0x1e, 0xc1, 0x14, 0x93, 0x84, 0xfc, 0x15,
	0x60, 0xe3, 0x46, 0x1b, 0x51, 0xe2, 0xb0, 0xda, 0x88, 0x12, 0xd2, 0xf1, 0xea, 0x0b, 0x74, 0x95,
	0xe4, 0xa7, 0xa6, 0x3f, 0x26, 0x68, 0xec, 0x87, 0x13, 0x8a, 0x08, 0x0e, 0xfc, 0x65, 0xf4, 0x24,
	0x3e, 0x45, 0x3c, 0xf4, 0x51, 0xf8, 0x21, 0x11, 0x92, 0x00, 0x95, 0xa6, 0xae, 0xc2, 0x7d, 0xae,
	0x16, 0xae, 0xa2, 0xe9, 0x3c, 0xb5, 0x9b, 0x8b, 0xbc, 0x95, 0xf4, 0x8e, 0xf7, 0x90, 0xa0, 0x71,
	0x37, 0xd7, 0x75, 0xf2, 0x3d, 0xed, 0x2b, 0x51, 0x7b, 0xa9, 0x31, 0x2e, 0x34, 0xbd, 0x51, 0x6a,
	0x17, 0xb2, 0x53, 0x5a, 0x9c, 0xea, 0x96, 0x9a, 0xea, 0x8b, 0x56, 0x6d, 0xac, 0xca, 0xbe, 0xf3,
	0xd4, 0x76, 0xff, 0x31, 0x58, 0xc9, 0x0a, 0xc7, 0x7b, 0xb4, 0x36, 0x5a, 0x77, 0x21, 0xbb, 0x36,
	0xdc, 0x33, 0xfd, 0xbe, 0x44, 0x3c, 0x02, 0x99, 0x9d, 0xa8, 0x9f, 0x08, 0x08, 0xd5, 0xf1, 0x0e,
	0x46, 0x2c, 0x38, 0x36, 0x6f, 0x1f, 0x6a, 0x8d, 0x0d, 0xef, 0x6e, 0x2e, 0x38, 0x42, 0xa2, 0x2f,
	0x20, 0xec, 0x01, 0xef, 0x64, 0x64, 0x5e, 0x3a, 0x34, 0x5e, 0x2b, 0xdd, 0xf6, 0xcd, 0x4a, 0xb7,
	0xee, 0x70, 0xad, 0x74, 0xeb, 0x64, 0x56, 0xba, 0x1c, 0x5d, 0x95, 0xae, 0xaf, 0xef, 0x62, 0x8a,
	0xa5, 0x0f, 0x14, 0xfb, 0x88, 0xb0, 0x84, 0x4a, 0x73, 0x47, 0x85, 0x68, 0x5e, 0xa6, 0x76, 0x91,
	0x9a, 0xa7, 0xf6, 0x7e, 0xee, 0x5e, 0x20, 0x1c, 0x6f, 0x3b, 0x43, 0x5e, 0x50, 0xdc, 0x56, 0xff,
	0xc6, 0x5b, 0xbd, 0xbe, 0x92, 0x84, 0x21, 0x07, 0x21, 0xcc, 0x5d, 0xe5, 0xeb, 0x66, 0xf7, 0xb5,
	0xc8, 0xad, 0xee, 0x6b, 0x91, 0x71, 0xbc, 0x9d, 0x2b, 0xe7, 0x1c, 0xe8, 0xb4, 0xcf, 0xa6, 0x96,
	0x76, 0x3e, 0xb5, 0xb4, 0xdf, 0x53, 0x4b, 0xfb, 0x3e, 0xb3, 0x6a, 0xe7, 0x33, 0xab, 0xf6, 0x6b,
	0x66, 0xd5, 0xde, 0x3d, 0x89, 0xb0, 0x1c, 0x26, 0x83, 0x56, 0xc0, 0x88, 0x0b, 0x14, 0x37, 0x83,
	0x21, 0xc2, 0xd4, 0x8d, 0x58, 0x33, 0x7b, 0x2d, 0xc7, 0xea, 0xbd, 0x94, 0x93, 0x18, 0xc4, 0x60,
	0x53, 0x3d, 0x87, 0x4f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x1e, 0xd2, 0xd3, 0x49, 0x05,
	0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InitEniAddress) > 0 {
		i -= len(m.InitEniAddress)
		copy(dAtA[i:], m.InitEniAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.InitEniAddress)))
		i--
		dAtA[i] = 0x7a
	}
	if len(m.InitEniAmount) > 0 {
		i -= len(m.InitEniAmount)
		copy(dAtA[i:], m.InitEniAmount)
		i = encodeVarintParams(dAtA, i, uint64(len(m.InitEniAmount)))
		i--
		dAtA[i] = 0x72
	}
	{
		size := m.MaximumFeePerGas.Size()
		i -= size
		if _, err := m.MaximumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x6a
	if m.TargetGasUsedPerBlock != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TargetGasUsedPerBlock))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.MaxDynamicBaseFeeDownwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeDownwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.MaxDynamicBaseFeeUpwardAdjustment.Size()
		i -= size
		if _, err := m.MaxDynamicBaseFeeUpwardAdjustment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.MinimumFeePerGas.Size()
		i -= size
		if _, err := m.MinimumFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BaseFeePerGas.Size()
		i -= size
		if _, err := m.BaseFeePerGas.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.PriorityNormalizer.Size()
		i -= size
		if _, err := m.PriorityNormalizer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PriorityNormalizer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.BaseFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinimumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDynamicBaseFeeUpwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxDynamicBaseFeeDownwardAdjustment.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.TargetGasUsedPerBlock != 0 {
		n += 1 + sovParams(uint64(m.TargetGasUsedPerBlock))
	}
	l = m.MaximumFeePerGas.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.InitEniAmount)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.InitEniAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriorityNormalizer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriorityNormalizer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BaseFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeUpwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeUpwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxDynamicBaseFeeDownwardAdjustment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxDynamicBaseFeeDownwardAdjustment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetGasUsedPerBlock", wireType)
			}
			m.TargetGasUsedPerBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TargetGasUsedPerBlock |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaximumFeePerGas", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaximumFeePerGas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitEniAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitEniAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitEniAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitEniAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
