global:
  scrape_interval: 10s  # scrape interval for all targets

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # monitoring prometheus itself
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']  # monitoring node exporter
  - job_name: 'cometbft'
    static_configs:
      - targets: ['localhost:26660']  # cometbft default port