global:
  scrape_interval: 15s  # 抓取间隔

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # 监控自身
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']  # 监控 Node Exporter
  - job_name: 'cosmos-tendermint'
    static_configs:
      - targets: ['172.21.117.51:26660']  # Tendermint 默认指标端点