global:
  scrape_interval: 15s  # 抓取间隔

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # monitoring prometheus itself
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']  # monitoring node exporter
  - job_name: 'cosmos-tendermint'
    static_configs:
      - targets: ['localhost:26660']  # cometbft default port