name: Go Build Check
on: [push]

jobs:
  build:
    name: Build with Go 1.24.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go 1.24.2
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/go/bin
            ${{ github.workspace }}/bin
          key: ${{ runner.os }}-go-${{ hashFiles('​**​/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build with Make
        run: make build