name: Compatibility Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - base
      - refactor**

jobs:
  forward-compatibility:
    name: forward-compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Configure git to use PAT
        run: |
          git config --global url."https://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@github.com".insteadOf "https://github.com"
      - name: Check Latest Dependencies
        run: |
          git clone https://github.com/sei-protocol/sei-cosmos.git
          git clone https://github.com/sei-protocol/sei-tendermint.git
          git clone https://github.com/sei-protocol/sei-iavl.git
          git clone https://github.com/sei-protocol/go-ethereum.git
          go mod edit -replace github.com/cosmos/iavl=./sei-iavl
          go mod edit -replace github.com/tendermint/tendermint=./sei-tendermint
          go mod edit -replace github.com/cosmos/cosmos-sdk=./sei-cosmos
          go mod edit -replace github.com/ethereum/go-ethereum=./go-ethereum
          go mod tidy
          make install
