name: Compatibility Check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - base
      - refactor**

jobs:
  forward-compatibility:
    name: forward-compatibility
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Check Latest Dependencies
        run: |
          git clone https://github.com/eni-chain/eni-cosmos.git
          git clone https://github.com/eni-chain/eni-tendermint.git
          git clone https://github.com/eni-chain/eni-iavl.git
          git clone https://github.com/eni-chain/go-ethereum.git
          go mod edit -replace github.com/cosmos/iavl=./eni-iavl
          go mod edit -replace github.com/tendermint/tendermint=./eni-tendermint
          go mod edit -replace github.com/cosmos/cosmos-sdk=./eni-cosmos
          go mod edit -replace github.com/ethereum/go-ethereum=./go-ethereum
          go mod tidy
          make install
