name: UnitTests

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test-and-coverage:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: Configure git to use PAT
        run: |
          git config --global url."https://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@github.com".insteadOf "https://github.com"

      - name: Run Go Tests
        run: go test -coverprofile cover_full.out ./...

      - name: Filter coverage file
        run: grep -v "mock\|pb.go" ./cover_full.out > ./cover.out

      - name: Check coverage
        run: |
          COVERAGE=$(go tool cover -func=cover.out | tail -1 | grep -P "\\d+\\.\\d+(?=\\%)" -o)
          echo "Code coverage is $COVERAGE%"
          if (( $(echo "$COVERAGE < 40" | bc -l) )); then
            echo "Code coverage is below 40% ($COVERAGE%)"
            exit 1
          fi